name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3
       with:
        fetch-depth: 0
       
       
     - name: Docker login
       env: 
        DOCKER_USER: ${{ secrets.DEVTALLES_DOCKER_COURSE_USER }}
        DOCKER_PASSWORD: ${{ secrets.DEVTALLES_DOCKER_COURSE_PASSWORD }}
       run:  |
        echo "Logging in"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Log in finished"
     
     
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
